### ISSUE TITLE
Cache busting issue

### ISSUE THREAD

**Issue by SETU-WEB** [meatpaste/ee-rocket-docs#5]
Hi Rodger 
I'm having some issues with cache busting with rocket. When I set it update on save to "Create new cache files when an entry is saved" I run into timeout issues on save as it hangs. If I set it to "Delete cache files on save but do not create new ones" I don't get the timeout issues but the bache doesn't bust . I'm presuming here that the first setting is a cache warming where the plugin creates the new cache file and with the second method the page remains uncached till until visited again .
I do run cloudflare on this site so maybe a conflict with cloudflare caching is happening here. I have excluded the rocket cache folder and its contents in my root for the cloudflare cache as I thought that was the problem but it didn't make a difference 
Have you come across issues with using rocket and cloudflare at the same time before or is there something else I'm missing 
Thanks
Brian

**Comment by SETU-WEB** [comment]
After a bit more investigation cache busting is working properly in my dev environment which runs under the same Cloudflare setup. The difference between them is the dev environment is running 2.1.3 and the live environment which is not cache busting is running 2.1.4 . Is there an issue with that update ?

**Comment by SETU-WEB** [comment]
I did some testing this morning and I can replicate the same issue using 2.1.4 on my local setup .So it looks like the cache not busting on save is a bug in this version

**Comment by meatpaste** [comment]
resolved in version 2.1.5

**Comment by SETU-WEB** [comment]
Hi Rodger 
I downloaded the latest version from the EE store and it hasn't resolved the issue. I think its still the older version in the store as the version number doesn't update when I update addons in the backend
Thanks
Brian

**Comment by meatpaste** [comment]
Cache deletion is resolved in the version you downloaded. TImeout issue is expected where entries appear on multiple pages (i've updated the readme).

**Comment by SETU-WEB** [comment]
Hi 
I just downloaded again from the purchases link on my EE account, and it still seems to be the 2.1.4. The change log in the readme isn't updated and again when I update the plugin in the control panel it's still 2.1.4. And of course, the cache still isn't busting on entry update.
I'm not sure what's happening here, do I need up renew my licence or something else 
Thanks
Brian 

![Screenshot 2022-02-28 230012](https://user-images.githubusercontent.com/8246895/156072783-e6baee30-b2ff-43bd-8133-44bb51f90f45.png)

**Comment by meatpaste** [comment]
Tried again with a different filename, any good?

**Comment by SETU-WEB** [comment]
Yes that sorted it, I downloaded it and it gave me the update option in the control panel.It sorted my cache busting issue
Thanks
Brian
